version: '3.9'

services:
  # nginx:
  #   build: .
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - php

  # php:
  #   build:
  #     context: dockerfiles/php
  #   volumes:
  #     - .:/var/www/html

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: currency_exchange
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.1.3-apache
    environment:
      - PMA_HOST=db
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    ports:
      - 8080:80

  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  redis:
  db:
    driver: local
