version: '3.9'

services:
  # nginx:
  #   build: .
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - php

  # php:
  #   build:
  #     context: dockerfiles/php
  #   volumes:
  #     - .:/var/www/html

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: currency_exchange
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.1.3-apache
    environment:
      - PMA_HOST=db
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    ports:
      - 8080:80

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db:
    driver: local

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
